### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by Rebecca-Hiscock** [MinchS/Discoloured-V2#2]
So this isn't really an issue, but I didn't know where else to write it. Please make sure to always get the LATEST version of the backgrounds, so check whenever you are on, in the assets folder. This goes for other sprites as well. 

For the backgrounds:
'bg' - background
'colour' or 'c'  - coloured version
'bw' - black and white version
Also, the higher the number, the newer it is. so, 'bg1.7colour', would be higher than 'bg1.6colour'. 

Sometimes the code might not be changed for the latest sprite, so try to keep older versions in a separate folder, maybe in your pictures library, just in case. 
We can keep older versions on GitHub, but it could be easier to delete them when new ones are made. Let me/everyone know what you think.

BTW - I added mountains for the latest sprite version, if you don't like the colour then let me know, and we can change it.

-Bec

Also, let me know when you've seen this.

**Comment by Fitzpamc** [comment]
私は見てしました。
